# @Time    : 2023/3/14 下午2:18
# @Author  : Boyang
# @Site    : 
# @File    : defaults.py
# @Software: PyCharm
from detectron2.config.defaults import _C
from detectron2.config import CfgNode as CN

# MODEL
_C.MODEL.META_ARCHITECTURE = "YOLOV3"
_C.MODEL.WEIGHT = "./config/yolov3.weights"

# BACKBONE
_C.MODEL.BACKBONE.NAME = "build_darknet53_fpn_backbone"
_C.MODEL.FREEZE_AT = 2

# DARKNET
_C.MODEL.DARKNET = CN()
_C.MODEL.DARKNET.NORM = "BN"
_C.MODEL.DARKNET.STEM_OUT_CHANNELS = 32
_C.MODEL.DARKNET.RES1_OUT_CHANNELS = 64
_C.MODEL.DARKNET.DEPTH = 53
_C.MODEL.DARKNET.OUT_FEATURES = ["res3", "res4", "res5"]

# ANCHOR_GENERATOR
_C.MODEL.ANCHOR_GENERATOR.NAME = "YoloAnchorGenerator"
_C.MODEL.ANCHOR_GENERATOR.OFFSET = 0.5
_C.MODEL.ANCHOR_GENERATOR.ANCHORS = ([[10, 13], [16, 30], [33, 23]],
                                     [[30, 61], [62, 45], [59, 119]],
                                     [[116, 90], [156, 198], [373, 326]])

# YOLO
_C.MODEL.YOLOV3 = CN()
_C.MODEL.YOLOV3.NORM = "BN"
_C.MODEL.YOLOV3.IN_FEATURES = ["p3", "p4", "p5"]
_C.MODEL.YOLOV3.NUM_CLASSES = 80
_C.MODEL.YOLOV3.TEST_SCORE_THRESH = 0.25
_C.MODEL.YOLOV3.TEST_NMS_THRESH = 0.5

# MATCHER
_C.MODEL.MATCHER = CN()
_C.MODEL.MATCHER.IGNORE_THRESHOLD = 0.5
_C.MODEL.MATCHER.LABELS = [-1, 0, 1]

# INPUT MOSAIC
_C.INPUT.MOSAIC = CN()
_C.INPUT.MOSAIC.ENABLE = False
_C.INPUT.MOSAIC.NUM_IMAGES = 4
_C.INPUT.MOSAIC.MOSAIC_WIDTH = 640
_C.INPUT.MOSAIC.MOSAIC_HEIGHT = 640
_C.INPUT.MOSAIC.POOL_CAPACITY = 10

# INPUT RANDOM AFFINE
_C.INPUT.RANDOM_AFFINE = CN()
_C.INPUT.RANDOM_AFFINE.ENABLE = False
_C.INPUT.RANDOM_AFFINE.TRANSLATE = 0.1
_C.INPUT.RANDOM_AFFINE.SCALE = 0.1
_C.INPUT.RANDOM_AFFINE.DEGREE = 0
_C.INPUT.RANDOM_AFFINE.SHEAR = 10.0
_C.INPUT.RANDOM_AFFINE.PERSPECTIVE = 0.0

# INPUT COLOR JITTER
_C.INPUT.COLOR_JITTER = CN()
_C.INPUT.COLOR_JITTER.ENABLE = False
_C.INPUT.COLOR_JITTER.HUE = 0.1
_C.INPUT.COLOR_JITTER.SATURATION = 1.5
_C.INPUT.COLOR_JITTER.EXPOSURE = 1.5

# INPUT LETTER BOX
_C.INPUT.LETTERBOX = CN()
_C.INPUT.LETTERBOX.ENABLE = False
_C.INPUT.LETTERBOX.WIDTH = 640
_C.INPUT.LETTERBOX.HEIGHT = 640
