MODEL:
  #  DEVICE: "cpu"
  META_ARCHITECTURE: "YoloV3"
  BACKBONE:
    NAME: "build_darknet53_fpn_backbone"
  DARKNET:
    STEM_OUT_CHANNELS: 32
    NORM: "BN"
    OUT_FEATURES: [ "d3", "d4", "d5" ]
  DARKNET_FPN:
    NAME: "build_darknet_fpn"
    IN_FEATURES: [ "d3", "d4", "d5" ]
    OUT_CHANNELS: [ 128, 256, 512 ]
    NORM: "BN"
  ANCHOR_GENERATOR:
    SIZE: [ [ [ 10,13 ],  [ 16,30 ],  [ 33,23 ] ],  [ [ 30,61 ],  [ 62,45 ],  [ 59,119 ] ],  [ [ 116,90 ],  [ 156,198 ],  [ 373,326 ] ] ]
  HEAD:
    IN_FEATURES: [ "p3", "p4", "p5" ]
#  YOLO:


#DATASETS:
#  TRAIN:
#  TEST:
#
#SOLVER:

INPUT:
  MIN_SIZE_TRAIN: (416,)

VERSION: 2