MODEL:
  DEVICE: "cpu"
  META_ARCHITECTURE: "YoloV3"
  BACKBONE:
    NAME: "build_darknet53_backbone"
  DARKNET:
    STEM_OUT_CHANNELS: 32
    NORM: "BN"
    OUT_FEATURES: [ "d3", "d4", "d5" ]
  FPN:
    NAME: "build_darknet_fpn"


#  YOLO:


#DATASETS:
#  TRAIN:
#  TEST:
#
#SOLVER:

INPUT:
  MIN_SIZE_TRAIN: (416,)

VERSION: 2