MODEL:
  #  DEVICE: "cpu"
  META_ARCHITECTURE: "YoloV3"
  BACKBONE:
    NAME: "build_darknet53_fpn_backbone"
  DARKNET:
    STEM_OUT_CHANNELS: 32
    NORM: "BN"
    OUT_FEATURES: [ "d3", "d4", "d5" ]
  DARKNET_FPN:
    NAME: "build_darknet_fpn"
    IN_FEATURES: [ "d3", "d4", "d5" ]
    OUT_CHANNELS: [ 128, 256, 512 ]
    NORM: "BN"
  ANCHOR_GENERATOR:
    NAME: "YoloAnchorGenerator"
    SIZES: !!python/object/apply:eval [ "[[(w*h)**(1.0/2) for w,h in item] for item in [[[10,13],[16,30],[33,23]],[[30,61],[62,45],[59,119]],[[116,90],[156,198],[373,326]]]]" ]
    ASPECT_RATIOS: !!python/object/apply:eval [ "[[h/w for w,h in item] for item in [[[10,13],[16,30],[33,23]],[[30,61],[62,45],[59,119]],[[116,90],[156,198],[373,326]]]]" ]
  YOLO:
    IN_FEATURES: [ "p3", "p4", "p5" ]
    NUM_CLASSES: 20
    IOU_THRESHOLD: 0.5
    IOU_LABELS: [ -1, 0, 1 ]


DATASETS:
  TRAIN: ("coco_2017_val",)

# DEBUG
DATALOADER:
  NUM_WORKERS: 0

SOLVER:
  IMS_PER_BATCH: 1
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000

INPUT:
  MIN_SIZE_TRAIN: (640,)
VERSION: 2